### ISSUE TITLE
run demo,but the miniprogram dont work

### ISSUE THREAD

**Issue by charjack** [wmpf/wmpf_demo_external#17]
run the demo ,see the tips as follow:
-----绑定ticket与appid------
success
-----激活设备中-----
init finish,err 0
------启动小程序-----

success

从wecooper上下载的wmpf_demo,然后在小米8手机上运行demo后的提示如上，但是实际微信阅读的小程序并未运行起来。

**Comment by simonla** [comment]
请贴下log吧

**Comment by charjack** [comment]
2020-02-13 17:38:03.843 5951-6079/com.tencent.wmpf.demo E/ljkRequestsRepo: getDeviceInfo: productId = 1040, deviceId = Demo_wx7643d5f831302ab0_1581586614_36058dd360, signature = MEUCIFl8GISxopOOQ3cfEC/k54Ib6694tuWqpSln58pqN4QVAiEA02XLpwP5TUTF1FwhYyUBykbTeWuJSdRRMgRtUCrlLjs=, keyVersion = 1, appIdList = ["wx7643d5f831302ab0"], expiredTimeMs = 1581586683843
2020-02-13 17:38:03.865 5951-6066/com.tencent.wmpf.demo I/IPC.IPCBridgeManager: [getIPCBridge] process:com.tencent.wmpf
2020-02-13 17:38:03.866 5951-6066/com.tencent.wmpf.demo I/IPC.ObjectRecycler: addIntoSet(com.tencent.wmpf)
2020-02-13 17:38:03.866 5951-6066/com.tencent.wmpf.demo I/IPC.IPCInvokeCallbackWrapper: keep ref of callback(219643081)
2020-02-13 17:38:03.874 5083-5096/com.tencent.ilink.ServiceProcess W/IlinkService: [, , 0]:Going to delete tdi sessions num:0
2020-02-13 17:38:03.886 4971-6067/com.tencent.wmpf W/System.err: java.lang.InterruptedException
2020-02-13 17:38:03.886 4971-6067/com.tencent.wmpf W/System.err:     at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2010)
2020-02-13 17:38:03.886 4971-6067/com.tencent.wmpf W/System.err:     at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2044)
2020-02-13 17:38:03.886 4971-6067/com.tencent.wmpf W/System.err:     at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:358)
2020-02-13 17:38:03.886 4971-6067/com.tencent.wmpf W/System.err:     at com.tencent.ilinkservice.b$a.run(IlinkApiTaskManager.java:66)
2020-02-13 17:38:04.126 4971-4971/com.tencent.wmpf D/IlinkServiceImpl: Process name is:com.tencent.wmpf
2020-02-13 17:38:04.126 4971-4971/com.tencent.wmpf D/IlinkServiceImpl: my process name is:com.tencent.wmpf
2020-02-13 17:38:04.129 5083-5083/com.tencent.ilink.ServiceProcess D/IlinkService: [, , 0]:Receive broadcast mypkgname:com.tencent.wmpf, sender:com.tencent.wmpf, sender process:com.tencent.wmpf
2020-02-13 17:38:04.131 4971-4971/com.tencent.wmpf D/IlinkServiceApiTask: add task to queue!
2020-02-13 17:38:04.131 4971-6080/com.tencent.wmpf D/IlinkServiceApiTask: Thread stop running wait service available 20s
2020-02-13 17:38:04.133 5083-5083/com.tencent.ilink.ServiceProcess D/IlinkService: [, , 0]:Receive com.tencent.ilinkservice.Ask and my version is:33554461
2020-02-13 17:38:04.134 4971-4971/com.tencent.wmpf D/IlinkServiceReceiver: Receive broadcast mypkgname:com.tencent.wmpf, sender:com.tencent.wmpf
2020-02-13 17:38:04.134 4971-4971/com.tencent.wmpf D/IlinkServiceReceiver: Receive com.tencent.ilinkservice.Answer and the version is:33554461
2020-02-13 17:38:04.274 4971-5005/com.tencent.wmpf D/IlinkServiceImpl: Running service version is equal or bigger than us just bind the service:com.tencent.wmpf
2020-02-13 17:38:04.279 4971-4971/com.tencent.wmpf D/IlinkServiceImpl: my process name is:com.tencent.wmpf, my cookie is:8bf758bceffa3df7a9d196f7db5e27e06555cb8c7373c10f3ae8685a8343af09, my package name is:com.tencent.wmpf
2020-02-13 17:38:04.279 4971-4971/com.tencent.wmpf D/IlinkServiceImpl: onServiceConnected finished
2020-02-13 17:38:04.279 4971-6080/com.tencent.wmpf D/IlinkServiceApiTask: wake up from wait signal
2020-02-13 17:38:04.279 4971-6080/com.tencent.wmpf D/IlinkServiceApiTask: get task from queue
2020-02-13 17:38:04.280 5083-5118/com.tencent.ilink.ServiceProcess D/IlinkService: [, , 0]:device callback one:com.tencent.wmpf
2020-02-13 17:38:04.282 4971-5804/com.tencent.wmpf D/IlinkServiceImpl: Receive onlogin complete:0
2020-02-13 17:38:04.283 4971-5804/com.tencent.wmpf D/IlinkServiceApiTask: add task to queue!
2020-02-13 17:38:04.283 4971-5804/com.tencent.wmpf D/IlinkServiceDevice: onLoginComplete error:0
2020-02-13 17:38:04.285 4971-6080/com.tencent.wmpf D/IlinkServiceApiTask: get task from queue
2020-02-13 17:38:04.286 5083-5096/com.tencent.ilink.ServiceProcess V/IlinkServiceImpl: [, , 0]:com.tencent.wmpf Receive onlogin complete:0
2020-02-13 17:38:04.382 5951-5983/com.tencent.wmpf.demo I/ljkFastExperience: success 激活: com.tencent.wmpf.proto.WMPFActivateDeviceResponse@77b8fce
2020-02-13 17:38:04.382 5951-5983/com.tencent.wmpf.demo E/ljkRequestsRepo: onSuccess    0
2020-02-13 17:38:04.384 5951-5951/com.tencent.wmpf.demo E/ljkApi: launchAppId =wx7643d5f831302ab0 path=  appType=0
2020-02-13 17:38:04.397 5951-5951/com.tencent.wmpf.demo E/ljk: result = true
2020-02-13 17:38:04.398 5951-6054/com.tencent.wmpf.demo I/IPC.IPCBridgeManager: [getIPCBridge] process:com.tencent.wmpf
2020-02-13 17:38:04.398 5951-6054/com.tencent.wmpf.demo I/IPC.ObjectRecycler: addIntoSet(com.tencent.wmpf)
2020-02-13 17:38:04.398 5951-6054/com.tencent.wmpf.demo I/IPC.IPCInvokeCallbackWrapper: keep ref of callback(107478524)
2020-02-13 17:38:04.405 5951-5983/com.tencent.wmpf.demo E/ljk: response = 0  no activate  10006

**Comment by charjack** [comment]
最好一行的log是在如下的地方打印的
    fun launchWxaApp(launchAppId: String, path: String, appType: Int = 0): Single<WMPFLaunchWxaAppResponse> {
        return Single.create {
            val request = WMPFLaunchWxaAppRequest()
            request.baseRequest = WMPFBaseRequestHelper.checked()
            // Launch target(wxa appId)
            // WARNING: hostAppIds and wxaAppIds are binded sets.
            request.appId = launchAppId // Binded with HOST_APPID: wx64b7714cf1f64585
            request.path = path
            request.appType = appType // 0-正式版 1-开发版 2-体验版
            Log.e("ljkApi","launchAppId ="+launchAppId+" path="+path+"  appType="+appType)
            val result = WMPFIPCInvoker.invokeAsync<IPCInvokerTask_LaunchWxaApp, WMPFLaunchWxaAppRequest,
                    WMPFLaunchWxaAppResponse>(
                    request,
                    IPCInvokerTask_LaunchWxaApp::class.java
            ) { response -> it.onSuccess(response)
                Log.e("ljk","response = "+response.describeContents()+"  "+response.baseResponse.errMsg+"  "+response.baseResponse.ret);
            }

            if (!result) {
                it.onError(Exception("invoke launchWxaApp fail"))
                Log.e("ljk","result = "+result);
            }else{
                Log.e("ljk","result = "+result);
            }
        }
    }

**Comment by charjack** [comment]
问题描述的有点问题
