### ISSUE TITLE
运行错误：java.lang.IllegalStateException: it.invokeToken must not be null

### ISSUE THREAD

**Issue by TaoHanny** [wmpf/wmpf_demo_external#20]
错误如下：
`2020-02-17 13:33:05.261 2313-2338/? D/NetSpeedController: mLastSpeed = 2895.314   currentSpeed = 0.0
    
    --------- beginning of main
2020-02-17 13:33:06.456 9713-9713/? I/IPC.ExecutorServiceCreatorImpl: newThread(thread : ThreadPool#Thread-2)
2020-02-17 13:33:06.456 9713-9778/? I/IPC.IPCBridgeManager: [getIPCBridge] process:com.tencent.wmpf
2020-02-17 13:33:06.456 9713-9778/? I/IPC.ObjectRecycler: addIntoSet(com.tencent.wmpf)
2020-02-17 13:33:06.456 9713-9778/? I/IPC.IPCInvokeCallbackWrapper: keep ref of callback(130117614)
2020-02-17 13:33:06.479 9713-9726/? E/FastExperienceActivity: error: java.lang.IllegalStateException: it.invokeToken must not be null
2020-02-17 13:33:08.269 2313-2338/? D/NetSpeedController: mLastSpeed = 0.0   currentSpeed = 546.9062
2020-02-17 13:33:10.203 8546-8546/com.tencent.ilink.ServiceProcess D/IlinkService: [, , 0]:Receive broadcast mypkgname:com.tencent.wmpf, sender:com.tencent.wmpf, sender process:null
2020-02-17 13:33:10.204 8546-8546/com.tencent.ilink.ServiceProcess D/IlinkService: [, , 0]:Alive msg send by ourself not need to handle!
2020-02-17 13:33:10.208 8546-8615/com.tencent.ilink.ServiceProcess D/IlinkService: [, , 0]:It is a timer alive task:18 and version is:33554461
2020-02-17 13:33:10.276 2313-2338/? D/NetSpeedController: mLastSpeed = 135.45818   currentSpeed = 0.0
2020-02-17 13:33:11.604 9713-9726/? I/IPC.IPCInvokeCallbackWrapper: release ref of callback(130117614)
2020-02-17 13:33:11.604 9713-9726/? I/IPC.ObjectRecycler: removeFromSet(com.tencent.wmpf)
2020-02-17 13:33:14.286 2313-2338/? D/NetSpeedController: mLastSpeed = 0.0   currentSpeed = 143.71259
2020-02-17 13:33:15.290 2313-2338/? D/NetSpeedController: mLastSpeed = 143.71259   currentSpeed = 0.0
2020-02-17 13:33:17.690 1293-1350/? W/Binder: Outgoing transactions from this process must be FLAG_ONEWAY`

之前已经跑通了体验版的小程序，现在需要输入的productId、signature等这些deviceInfo参数我也写入了，并且根据文档返回了
![image](https://user-images.githubusercontent.com/30739724/74634476-e2349180-519e-11ea-8881-482fb2209c8e.png)，所以我的公私钥和signture肯定没有问题。同时DeivceID也已经注册成功，返回了OK
![image](https://user-images.githubusercontent.com/30739724/74634614-317ac200-519f-11ea-84b6-a2015f6f1bae.png)

所以，我不知道为什么还会出现这个错误。错误给的也不详细，完全不知道是哪个参数或者哪一步校验失败导致的这个问题。

**Comment by TaoHanny** [comment]
补充一下，我当前已完成在体验模式下的测试需要，现在需要通过输入自己的signture和appID+appsecrpt等必要参数,进行开发者模式的验证

**Comment by simonla** [comment]
pull一下最新的demo代码试试

**Comment by TaoHanny** [comment]
> pull一下最新的demo代码试试

我试过了，还是老问题，我的代码已经很新了。这个有没有什么调试工具，能供我们测试一下是什么环节的问题？

**Comment by TaoHanny** [comment]
我梳理了一下整个硬件注册的环节，觉得唯一可以出错的地方就是model name这个环节。所以想请问一下，在activateDevice这个一TASK中，会验证model name吗？如果说这一步会验证model name值的话，本地设备上的model name值是如何与微信终端平台上审核通过的model name进行校验的，同时这个应用是怎么调取本地model name值的？

**Comment by simonla** [comment]
设个错误一般是DeviceInfo错误导致的

运行activateDevice这个TASK，按com.tencent.ilink.ServiceProcess过滤log看看是否有异常

**Comment by TaoHanny** [comment]
> 设个错误一般是DeviceInfo错误导致的
> 
> 运行activateDevice这个TASK，按com.tencent.ilink.ServiceProcess过滤log看看是否有异常


我试过了，如果不通过体验版启动小程序，只通过开发者模式启动的话，com.tencent.ilink.ServiceProcess没有被拉起来。只有一个com.tencent.wmpf进程。我通过`com.tencent`为关键字过滤整个操作过程的log如下：  
```
2020-02-18 18:31:20.839 13559-13559/com.tencent.wmpf.demo I/MMKV: <MMKV.cpp:335::loadFromFile> loading [Constants] with 0 size in total, file size is 4096, InterProcess 0
2020-02-18 18:31:20.839 13559-13559/com.tencent.wmpf.demo I/MMKV: <MMKV.cpp:380::loadFromFile> loaded [Constants] with 0 values
2020-02-18 18:31:20.849 1307-11293/? D/NubiaSelfStartUtil: isRunningApp pkgName = com.tencent.wmpfresult  = true
2020-02-18 18:31:20.859 13472-13531/com.tencent.wmpf I/IPCThreadState: Application, mCallingUid=10354, descriptor=android.content.IContentProvider, code=1
    
beginning of system
2020-02-18 18:31:20.861 13472-13531/com.tencent.wmpf E/SchedPolicy: set_thread_freeze_state, freeze=0, pid=13472, num=35
2020-02-18 18:31:20.881 13559-13559/com.tencent.wmpf.demo I/IPC.ExecutorServiceCreatorImpl: createHandlerThread(hash : 22042818)
2020-02-18 18:31:20.883 13559-13653/com.tencent.wmpf.demo I/IPC.ThreadPool: createHandlerThread(id : 13653)
2020-02-18 18:31:20.884 13559-13559/com.tencent.wmpf.demo I/IPC.ThreadPool: initialize IPCInvoker ThreadPool(hashCode : 38606547)
2020-02-18 18:31:20.885 13559-13559/com.tencent.wmpf.demo I/IPC.ExecutorServiceCreatorImpl: newThread(thread : ThreadPool#Thread-0)
2020-02-18 18:31:20.888 13559-13654/com.tencent.wmpf.demo I/IPC.IPCBridgeManager: [getIPCBridge] process:com.tencent.wmpf
2020-02-18 18:31:20.892 13559-13654/com.tencent.wmpf.demo I/IPC.IPCBridgeManager: bindService(bw : 69689148, tid : 506, intent : Intent { cmp=com.tencent.wmpf/.app.WMPFService })
2020-02-18 18:31:20.894 1307-11293/? D/NubiaSelfStartUtil: isRunningApp pkgName = com.tencent.wmpfresult  = true
2020-02-18 18:31:20.912 13559-13559/com.tencent.wmpf.demo I/IPC.IPCBridgeManager: onServiceConnected(69689148)
2020-02-18 18:31:20.915 13559-13654/com.tencent.wmpf.demo I/IPC.ObjectRecycler: addIntoSet(com.tencent.wmpf)
2020-02-18 18:31:20.916 13559-13654/com.tencent.wmpf.demo I/IPC.IPCInvokeCallbackWrapper: keep ref of callback(145306408)
2020-02-18 18:31:20.962 13559-13615/com.tencent.wmpf.demo I/DocumentActivity: success: 10007 invalid data 
2020-02-18 18:31:20.962 13559-13615/com.tencent.wmpf.demo I/DocumentActivity: success: null 
2020-02-18 18:31:20.963 13559-13615/com.tencent.wmpf.demo W/System.err: java.lang.IllegalStateException: it.invokeToken must not be null
2020-02-18 18:31:20.963 13559-13615/com.tencent.wmpf.demo W/System.err:     at com.tencent.wmpf.demo.ui.DocumentActivity$onCreate$1$1.accept(DocumentActivity.kt:27)
2020-02-18 18:31:20.963 13559-13615/com.tencent.wmpf.demo W/System.err:     at com.tencent.wmpf.demo.ui.DocumentActivity$onCreate$1$1.accept(DocumentActivity.kt:15)
2020-02-18 18:31:20.963 13559-13615/com.tencent.wmpf.demo W/System.err:     at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:63)
2020-02-18 18:31:20.963 13559-13615/com.tencent.wmpf.demo W/System.err:     at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)
2020-02-18 18:31:20.964 13559-13615/com.tencent.wmpf.demo W/System.err:     at com.tencent.wmpf.demo.Api$activateDevice$1$result$1.onCallback(Api.kt:37)
2020-02-18 18:31:20.964 13559-13615/com.tencent.wmpf.demo W/System.err:     at com.tencent.wmpf.demo.Api$activateDevice$1$result$1.onCallback(Api.kt:31)
2020-02-18 18:31:20.964 13559-13615/com.tencent.wmpf.demo W/System.err:     at com.tencent.mm.ipcinvoker.IPCInvoker$IPCInvokeCallbackWrapper.onCallback(IPCInvoker.java:193)
2020-02-18 18:31:20.964 13559-13615/com.tencent.wmpf.demo W/System.err:     at com.tencent.mm.ipcinvoker.aidl.AIDL_IPCInvokeCallback$Stub.onTransact(AIDL_IPCInvokeCallback.java:57)
2020-02-18 18:31:20.964 13559-13615/com.tencent.wmpf.demo W/System.err:     at android.os.Binder.execTransact(Binder.java:714)
2020-02-18 18:31:20.964 13559-13615/com.tencent.wmpf.demo W/System.err: Application uncaught exception in thread "Binder:13559_4" java.lang.IllegalStateException: it.invokeToken must not be null
2020-02-18 18:31:20.965 13559-13615/com.tencent.wmpf.demo W/System.err:     at com.tencent.wmpf.demo.ui.DocumentActivity$onCreate$1$1.accept(DocumentActivity.kt:27)
2020-02-18 18:31:20.965 13559-13615/com.tencent.wmpf.demo W/System.err:     at com.tencent.wmpf.demo.ui.DocumentActivity$onCreate$1$1.accept(DocumentActivity.kt:15)
2020-02-18 18:31:20.965 13559-13615/com.tencent.wmpf.demo W/System.err:     at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:63)
2020-02-18 18:31:20.965 13559-13615/com.tencent.wmpf.demo W/System.err:     at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)
2020-02-18 18:31:20.965 13559-13615/com.tencent.wmpf.demo W/System.err:     at com.tencent.wmpf.demo.Api$activateDevice$1$result$1.onCallback(Api.kt:37)
2020-02-18 18:31:20.965 13559-13615/com.tencent.wmpf.demo W/System.err:     at com.tencent.wmpf.demo.Api$activateDevice$1$result$1.onCallback(Api.kt:31)
2020-02-18 18:31:20.966 13559-13615/com.tencent.wmpf.demo W/System.err:     at com.tencent.mm.ipcinvoker.IPCInvoker$IPCInvokeCallbackWrapper.onCallback(IPCInvoker.java:193)
2020-02-18 18:31:20.966 13559-13615/com.tencent.wmpf.demo W/System.err:     at com.tencent.mm.ipcinvoker.aidl.AIDL_IPCInvokeCallback$Stub.onTransact(AIDL_IPCInvokeCallback.java:57)
2020-02-18 18:31:20.966 13559-13615/com.tencent.wmpf.demo W/System.err:     at android.os.Binder.execTransact(Binder.java:714)
2020-02-18 18:31:20.982 1307-11293/? W/ActivityManager:   Force finishing activity com.tencent.wmpf.demo/.ui.DocumentActivity
2020-02-18 18:31:20.999 13559-13615/com.tencent.wmpf.demo I/Process: Sending signal. PID: 13559 SIG: 9
2020-02-18 18:31:21.012 1307-2008/? W/InputDispatcher: channel 'a92595 com.tencent.wmpf.demo/com.tencent.wmpf.demo.ui.DocumentActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2020-02-18 18:31:21.012 1307-2008/? E/InputDispatcher: channel 'a92595 com.tencent.wmpf.demo/com.tencent.wmpf.demo.ui.DocumentActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-02-18 18:31:21.012 1307-2008/? W/InputDispatcher: channel '842eef4 com.tencent.wmpf.demo/com.tencent.wmpf.demo.ui.GuideActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2020-02-18 18:31:21.013 1307-2008/? E/InputDispatcher: channel '842eef4 com.tencent.wmpf.demo/com.tencent.wmpf.demo.ui.GuideActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-02-18 18:31:21.017 1307-11288/? I/WindowManager: WIN DEATH: Window{a92595 u0 com.tencent.wmpf.demo/com.tencent.wmpf.demo.ui.DocumentActivity}
2020-02-18 18:31:21.017 1307-11288/? W/InputDispatcher: Attempted to unregister already unregistered input channel 'a92595 com.tencent.wmpf.demo/com.tencent.wmpf.demo.ui.DocumentActivity (server)'
2020-02-18 18:31:21.017 1307-2387/? I/ActivityManager: Process com.tencent.wmpf.demo (pid 13559) has died: fore TOP 
2020-02-18 18:31:21.018 1307-2387/? D/NubiaSelfStartUtil: isRunningApp pkgName = com.tencent.wmpf.demoresult  = false
2020-02-18 18:31:21.018 1307-2387/? D/NubiaSelfStartUtil: Not allow packageName==com.tencent.wmpf.demo from restartservice autostart
2020-02-18 18:31:21.019 1307-11302/? I/WindowManager: WIN DEATH: Window{842eef4 u0 com.tencent.wmpf.demo/com.tencent.wmpf.demo.ui.GuideActivity}
2020-02-18 18:31:21.020 1307-11302/? W/InputDispatcher: Attempted to unregister already unregistered input channel '842eef4 com.tencent.wmpf.demo/com.tencent.wmpf.demo.ui.GuideActivity (server)'
2020-02-18 18:31:21.038 1307-2387/? I/ActivityManager: Start proc 13662:com.tencent.wmpf.demo/u0a354 for activity com.tencent.wmpf.demo/.ui.GuideActivity
2020-02-18 18:31:21.112 13662-13662/? W/System: in loadDexFile: /data/app/com.tencent.wmpf.demo-R7AYGsZykRJez5bysY5uTg==/base.apk
2020-02-18 18:31:21.135 13662-13662/? I/MMKV: <MMKV.cpp:206::initializeMMKV> root dir: /data/user/0/com.tencent.wmpf.demo/files/mmkv
2020-02-18 18:31:21.136 13662-13662/? I/System.out: mmkv root: /data/user/0/com.tencent.wmpf.demo/files/mmkv
2020-02-18 18:31:21.153 13662-13662/? I/IPC.IPCInvokerBoot: setup IPCInvoker(process : com.tencent.wmpf.demo, application : 54505605)
2020-02-18 18:31:21.492 1307-1354/? I/ActivityManager: Displayed com.tencent.wmpf.demo/.ui.GuideActivity: +467ms
2020-02-18 18:31:52.960 13472-13531/com.tencent.wmpf I/IPCThreadState: Application
2020-02-18 18:31:52.964 13472-13531/com.tencent.wmpf E/SchedPolicy: set_thread_freeze_state, freeze=1, pid=13472, num=38`
```

如果说是由于我这边参数的错误导致的话，那是否是由于我提交审核设备时，输入的公钥的格式不对，我按照注册文档生成公钥之后并没有更改格式，直接复制进去，格式如下：  
![image](https://user-images.githubusercontent.com/30739724/74728633-1fbc1c00-527e-11ea-9bfd-e8e8cd044a23.png)
