### ISSUE TITLE
扫码登陆后，调用Api.launchWxaApp（），微信小程序闪退

### ISSUE THREAD

**Issue by TaoHanny** [wmpf/wmpf_demo_external#43]
我在使用Api.authorize（）拉起二维码界面并扫码通过后，调用Api.launchWxaApp（），报如下错误：

```
03-10 14:43:41.885 2327-2475/com.tencent.wmpf:container I/MagicBrush: [MBRuntime] Setup commandbuffer now...
03-10 14:43:41.900 2327-2475/com.tencent.wmpf:container I/MagicBrush: [MBRuntime] Setup comandbuffer success
03-10 14:43:41.901 2327-2475/com.tencent.wmpf:container I/MagicBrush: [MBRuntime] Setup gfx success
03-10 14:43:41.901 2327-2475/com.tencent.wmpf:container I/MagicBrush: [MBRuntime] Binding Finished. NativeGlobal prepared.
03-10 14:43:41.960 2327-2342/com.tencent.wmpf:container I/art: Background partial concurrent mark sweep GC freed 12402(537KB) AllocSpace objects, 5(5MB) LOS objects, 36% free, 28MB/44MB, paused 5.628ms total 44.685ms
03-10 14:43:41.962 2327-2327/com.tencent.wmpf:container D/cr_BuildInfo: [BuildInfo.java:113] GMS package is not found.
    android.content.pm.PackageManager$NameNotFoundException: com.google.android.gms
        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:115)
        at org.chromium.base.BuildInfo.<init>(BuildInfo.java:111)
        at org.chromium.base.BuildInfo.<init>(BuildInfo.java:21)
        at org.chromium.base.BuildInfo$Holder.<clinit>(BuildInfo.java:53)
        at org.chromium.base.BuildInfo.getInstance(BuildInfo.java:84)
        at org.chromium.base.BuildInfo.getAll(BuildInfo.java:57)
        at org.chromium.content.browser.BrowserStartupController.nativeSetCommandLineFlags(Native Method)
        at org.chromium.content.browser.BrowserStartupController.prepareToStartBrowserProcess(BrowserStartupController.java:346)
        at org.chromium.content.browser.BrowserStartupController.startBrowserProcessesSync(BrowserStartupController.java:224)
        at org.xwalk.core.internal.XWalkViewDelegate$1.run(XWalkViewDelegate.java:482)
        at org.chromium.base.ThreadUtils.runOnUiThreadBlocking(ThreadUtils.java:74)
        at org.xwalk.core.internal.XWalkViewDelegate.startBrowserProcess(XWalkViewDelegate.java:437)
        at org.xwalk.core.internal.XWalkViewDelegate.init(XWalkViewDelegate.java:230)
        at org.xwalk.core.internal.XWalkViewInternal.initXWalkContent(XWalkViewInternal.java:389)
        at org.xwalk.core.internal.XWalkViewInternal.<init>(XWalkViewInternal.java:302)
        at org.xwalk.core.internal.XWalkViewBridge.<init>(XWalkViewBridge.java:37)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at org.xwalk.core.ReflectConstructor.newInstance(SourceFile:48)
        at org.xwalk.core.XWalkView.reflectionInit(SourceFile:2511)
        at org.xwalk.core.XWalkView.<init>(SourceFile:268)
        at com.tencent.xweb.xwalk.j$b.<init>(SourceFile:138)
        at com.tencent.xweb.xwalk.j.<init>(SourceFile:985)
        at com.tencent.xweb.xwalk.XWalkWebFactory.createWebView(SourceFile:167)
        at com.tencent.xweb.internal.h.a(SourceFile:119)
        at com.tencent.xweb.WebView.a(SourceFile:407)
        at com.tencent.xweb.WebView.<init>(SourceFile:297)
        at com.tencent.xweb.WebView.<init>(SourceFile:292)
        at com.tencent.xweb.WebView.<init>(SourceFile:288)
        at com.tencent.xweb.WebView.<init>(SourceFile:284)
        at com.tencent.mm.plugin.appbrand.page.bj.<init>(XWebViewImpl.java:99)
        at com.tencent.luggage.l.g.b.b(MPPageViewRendererStandaloneXWebImpl.java:38)
        at com.tencent.mm.plugin.appbrand.page.at.c(MPPageViewRenderer.java:13236)
        at com.tencent.mm.plugin.appbrand.page.a.a(AbstractMPPageViewRenderer.java:313)
        at com.tencent.mm.plugin.appbrand.page.t.c(AppBrandPageView.java:25430)
        at com.tencent.mm.plugin.appbrand.jsapi.d.K(AppBrandComponentImpl.java:124)
        at com.tencent.mm.plugin.appbrand.page.t.s(AppBrandPageView.java:210)
        at com.tencent.wmpf.g.f$3$2$1.run(WMPFBaseRuntime.java:237)
        at com.tencent.mm.plugin.appbrand.d.a(AppBrandRuntime.java:1272)
        at com.tencent.wmpf.g.f$3$2.run(WMPFBaseRuntime.java:2259)
        at com.tencent.wmpf.g.f$3$3.a(WMPFBaseRuntime.java:249)
        at com.tencent.luggage.l.a.d.a(XWebPreloader.java:64)
        at com.tencent.wmpf.g.f$3.a(WMPFBaseRuntime.java:246)
        at com.tencent.mm.plugin.appbrand.d$12.run(AppBrandRuntime.java:1342)
        at com.tencent.luggage.sdk.h.b.a(Profile.kt:25)
        at com.tencent.mm.plugin.appbrand.d.z(AppBrandRuntime.java:237)
        at com.tencent.mm.plugin.appbrand.e.a(AppBrandRuntimeContainer.java:199)
        at com.tencent.luggage.sdk.f.a.a(AppBrandRuntimeContainerLU.java:20)
        at com.tencent.luggage.sdk.f.a$1.run(AppBrandRuntimeContainerLU.java:51)
        at android.app.Activity.runOnUiThread(Activity.java:5502)
        at com.tencent.luggage.sdk.f.a.a(AppBrandRuntimeContainerLU.java:35)
        at com.tencent.luggage.e.a.a(AppBrandRuntimeContainerStandaloneImpl.java:5028)
        at com.tencent.luggage.e.a$1.run(AppBrandRuntimeContainerStandaloneImpl.java:81)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5285)
    	at java.lang.reflect.Method.invo
03-10 14:43:42.053 2327-2327/com.tencent.wmpf:container I/ActivityWindowAndroid: ActivityWindowAndroid: not activity
03-10 14:43:42.076 2327-2489/com.tencent.wmpf:container D/ConnectivityManager.CallbackHandler: CM callback handler got msg 524290
03-10 14:43:42.178 2327-2327/com.tencent.wmpf:container W/art: Attempt to remove local handle scope entry from IRT, ignoring
03-10 14:43:42.352 2327-2327/com.tencent.wmpf:container W/System.err: java.lang.UnsupportedOperationException: class org.xwalk.core.internal.XWalkViewBridge.setExtendTextAreaClientSuper
03-10 14:43:42.352 2327-2327/com.tencent.wmpf:container W/System.err:     at org.xwalk.core.ReflectMethod.invoke(SourceFile:57)
03-10 14:43:42.352 2327-2327/com.tencent.wmpf:container W/System.err:     at org.xwalk.core.XWalkView.setExtendTextAreaClient(SourceFile:1397)
03-10 14:43:42.352 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.mm.plugin.appbrand.page.bj.<init>(XWebViewImpl.java:2073)
03-10 14:43:42.352 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.luggage.l.g.b.b(MPPageViewRendererStandaloneXWebImpl.java:38)
03-10 14:43:42.352 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.mm.plugin.appbrand.page.at.c(MPPageViewRenderer.java:13236)
03-10 14:43:42.352 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.mm.plugin.appbrand.page.a.a(AbstractMPPageViewRenderer.java:313)
03-10 14:43:42.352 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.mm.plugin.appbrand.page.t.c(AppBrandPageView.java:25430)
03-10 14:43:42.352 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.mm.plugin.appbrand.jsapi.d.K(AppBrandComponentImpl.java:124)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.mm.plugin.appbrand.page.t.s(AppBrandPageView.java:210)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.wmpf.g.f$3$2$1.run(WMPFBaseRuntime.java:237)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.mm.plugin.appbrand.d.a(AppBrandRuntime.java:1272)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.wmpf.g.f$3$2.run(WMPFBaseRuntime.java:2259)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.wmpf.g.f$3$3.a(WMPFBaseRuntime.java:249)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.luggage.l.a.d.a(XWebPreloader.java:64)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.wmpf.g.f$3.a(WMPFBaseRuntime.java:246)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.mm.plugin.appbrand.d$12.run(AppBrandRuntime.java:1342)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.luggage.sdk.h.b.a(Profile.kt:25)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.mm.plugin.appbrand.d.z(AppBrandRuntime.java:237)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.mm.plugin.appbrand.e.a(AppBrandRuntimeContainer.java:199)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.luggage.sdk.f.a.a(AppBrandRuntimeContainerLU.java:20)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.luggage.sdk.f.a$1.run(AppBrandRuntimeContainerLU.java:51)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at android.app.Activity.runOnUiThread(Activity.java:5502)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.luggage.sdk.f.a.a(AppBrandRuntimeContainerLU.java:35)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.luggage.e.a.a(AppBrandRuntimeContainerStandaloneImpl.java:5028)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at com.tencent.luggage.e.a$1.run(AppBrandRuntimeContainerStandaloneImpl.java:81)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at android.os.Looper.loop(Looper.java:135)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5285)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:971)
03-10 14:43:42.353 2327-2327/com.tencent.wmpf:container W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)
03-10 14:43:42.365 2327-2500/com.tencent.wmpf:container E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
03-10 14:43:42.380 2327-2484/com.tencent.wmpf:container D/BluetoothAdapter: 303234748: getState() :  mService = null. Returning STATE_OFF
03-10 14:43:42.393 2327-2327/com.tencent.wmpf:container I/MMKV: <MMKV.cpp:206::initializeMMKV> root dir: /data/data/com.tencent.wmpf/files/mmkv
03-10 14:43:42.433 2327-2500/com.tencent.wmpf:container W/VideoCapabilities: Unsupported mime video/mpeg2
03-10 14:43:42.441 2327-2500/com.tencent.wmpf:container W/VideoCapabilities: Unsupported mime video/flv
03-10 14:43:42.443 2327-2327/com.tencent.wmpf:container I/Choreographer: Skipped 42 frames!  The application may be doing too much work on its main thread.
03-10 14:43:42.445 2327-2500/com.tencent.wmpf:container W/VideoCapabilities: Unsupported mime video/mjpeg
03-10 14:43:42.453 2327-2327/com.tencent.wmpf:container D/ViewRootImpl: 1080<<<<<< BACK FROM relayoutWM.LayoutParams{(0,0)(fillxfill)mPosX=0mPosY=0mHScale=1.0mVScale=1.0 align=UNDEFINE taskId=966 sim=#110 ty=1 fl=#81810100 fmt=-2 wanim=0x1030469 sysuil=true surfaceInsets=Rect(0, 0 - 0, 0) needsMenuKey=2packageName=com.tencent.wmpftoken=android.os.BinderProxy@2b7cb32b}
03-10 14:43:42.456 2327-2500/com.tencent.wmpf:container W/VideoCapabilities: Unsupported mime video/flv
03-10 14:43:42.457 2327-2500/com.tencent.wmpf:container W/VideoCapabilities: Unsupported mime video/mpeg2
03-10 14:43:42.459 2327-2500/com.tencent.wmpf:container W/VideoCapabilities: Unsupported mime video/vc1
03-10 14:43:42.464 2327-2500/com.tencent.wmpf:container W/VideoCapabilities: Unsupported mime video/mjpeg
03-10 14:43:42.470 2327-2500/com.tencent.wmpf:container W/AudioCapabilities: Unsupported mime audio/wav
03-10 14:43:42.477 2327-2500/com.tencent.wmpf:container I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
03-10 14:43:42.824 2327-2489/com.tencent.wmpf:container D/ConnectivityManager.CallbackHandler: CM callback handler got msg 524290
03-10 14:43:42.882 2327-2327/com.tencent.wmpf:container D/ViewRootImpl: 1080<<<<<< BACK FROM relayoutWM.LayoutParams{(0,0)(fillxfill)mPosX=0mPosY=0mHScale=1.0mVScale=1.0 align=UNDEFINE taskId=966 sim=#110 ty=1 fl=#81810100 fmt=-2 wanim=0x1030469 sysuil=true surfaceInsets=Rect(0, 0 - 0, 0) needsMenuKey=2packageName=com.tencent.wmpftoken=android.os.BinderProxy@2b7cb32b}
03-10 14:43:42.972 2327-2327/com.tencent.wmpf:container I/WMPF.XwebCameraUtil: isUseXwebCamera:true
```
发现报缺少google的GMS包，谷歌的GMS包在国内一般都被去掉了吧？这个问题能进行优化一下吗？

**Comment by simonla** [comment]
看起来并不是crash的堆栈，麻烦发送sdcard/wmpf/xlog目录下的日志文件到complexzeng@tencent.com，我排查一下，万分感谢~

**Comment by TaoHanny** [comment]
> 看起来并不是crash的堆栈，麻烦发送sdcard/wmpf/xlog目录下的日志文件到[complexzeng@tencent.com](mailto:complexzeng@tencent.com)，我排查一下，万分感谢~

已将问题包发送至您的邮箱，感谢您的帮助！

**Comment by simonla** [comment]
看了日志后发现是更换了deviceID打开小程序（如果走快速体验，更换打开的小程序就会更换deviceID）

这里设计上是不允许运行中动态的更改deviceID，否则会出现激活信息不一致的问题

目前要解决这个问题，你需要在设置里清空「微信小程序硬件框架」的存储

未来我们加一个保护，检测到deviceID更改后，就清空激活信息，然后重启WMPF进程

**Comment by TaoHanny** [comment]
更新RC3后，没有再出现扫码登陆crash的问题，此问题解决

**Comment by TaoHanny** [comment]
更新RC3后，没有再出现扫码登陆crash的问题，此问题解决
