### ISSUE TITLE
华为mate20 pro和 小米4c都打不开demo

### ISSUE THREAD

**Issue by SongRainRay** [wmpf/wmpf_demo_external#93]
`08-28 20:02:10.489 19255 19297 I IlinkService: [, , 0]:device callback one:com.tencent.wmpf
08-28 20:02:10.586 19328 19328 W System.err: 	at com.tencent.wmpf.h.k$4$2$1.run(WMPFBaseRuntime.java:263)
08-28 20:02:10.586 19328 19328 W System.err: 	at com.tencent.wmpf.h.k$4$2.run(WMPFBaseRuntime.java:2317)
08-28 20:02:10.586 19328 19328 W System.err: 	at com.tencent.wmpf.h.k$4$3.a(WMPFBaseRuntime.java:275)
08-28 20:02:10.586 19328 19328 W System.err: 	at com.tencent.wmpf.h.k$4.a(WMPFBaseRuntime.java:272)
08-28 20:02:10.618 19328 20110 D HiTouch_PressGestureDetector: onAttached, package=com.tencent.wmpf, windowType=1, mHiTouchRestricted=false
`

现象是能打开小程序启动页看到图标，然后直接闪退。
**手机型号**：
华为Mate20 Pro，android 10
小米4c，android 7.0

**Comment by SongRainRay** [comment]
08-28 20:02:10.489 19255 19297 I IlinkService: [, , 0]:device callback one:com.tencent.wmpf
08-28 20:02:10.586 19328 19328 W System.err: 	at com.tencent.wmpf.h.k$4$2$1.run(WMPFBaseRuntime.java:263)
08-28 20:02:10.586 19328 19328 W System.err: 	at com.tencent.wmpf.h.k$4$2.run(WMPFBaseRuntime.java:2317)
08-28 20:02:10.586 19328 19328 W System.err: 	at com.tencent.wmpf.h.k$4$3.a(WMPFBaseRuntime.java:275)
08-28 20:02:10.586 19328 19328 W System.err: 	at com.tencent.wmpf.h.k$4.a(WMPFBaseRuntime.java:272)
08-28 20:02:10.618 19328 20110 D HiTouch_PressGestureDetector: onAttached, package=com.tencent.wmpf, windowType=1, mHiTouchRestricted=false

**Comment by ggp111** [comment]
我和你是一样的现象，点击启动之后会闪退，手机型号是红米K20 PRO，部分日志信息如下

D/RequestsRepo: getDeviceInfo: productId = 1040, deviceId = Demo_wxa75efa648b60994b_1599189016_9ba060bc59, signature = MEQCIDHStqbZmr9OEXJG0Q//dbTjTWJC+BG3RgCp+FrvXlWTAiB742j25k6B8XbN7/BUB+wkMBhEXcR4ZacO0eXlIZmRGQ==, keyVersion = 1, appIdList = ["wxa75efa648b60994b"], expiredTimeMs = 1599189056502
I/Demo.Api: activateDevice: isInProductionEnv = false
I/IPC.IPCBridgeManager: [getIPCBridge] process:com.tencent.wmpf
I/IPC.IPCBridgeManager: pingBinder:true
I/IPC.ObjectRecycler: addIntoSet(com.tencent.wmpf)
I/IPC.IPCInvokeCallbackWrapper: keep ref of callback(26769508)
I/MicroMsg.ExperienceActivity: success: com.tencent.wmpf.proto.WMPFActivateDeviceResponse@3f1eacd
I/Demo.Api: launchWxaApp: appId = wxa75efa648b60994b, hostAppID = wx94ef6bb77b573d05, deviceId = Demo_wxa75efa648b60994b_1599189016_9ba060bc59
I/IPC.IPCBridgeManager: [getIPCBridge] process:com.tencent.wmpf
I/IPC.IPCBridgeManager: pingBinder:true
I/IPC.ObjectRecycler: addIntoSet(com.tencent.wmpf)
I/IPC.IPCInvokeCallbackWrapper: keep ref of callback(151959187)
I/DocumentActivity: success: 0 ok

**Comment by Hazy-Huang** [comment]
麻烦确认一下：
1.启动有两个apk的，确定小程序框架这个apk没有启动，必须启动小程序框架这个apk再启动这个wmpf才有会启动的
2.确定这两个apk的权限，在看下权限是否全部提供
3.体验demo暂时只支持正式版小程序，体验版、开发版的小程序后续才会支持

**Comment by charlesYun** [comment]
请问一下这个WeCooper，在iOS手机上面支持吗
